// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzIDcA8wWusgIfQ4vwZJWysAEUqAf2DWY',
    appId: '1:309940397515:android:3ef8bfe6b233229bb3c24e',
    messagingSenderId: '309940397515',
    projectId: 'moviemio-app',
    storageBucket: 'moviemio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAblwgjsyNWuDtm1GFRnO4OqsWqT_B3G8A',
    appId: '1:309940397515:ios:4730895756b32caab3c24e',
    messagingSenderId: '309940397515',
    projectId: 'moviemio-app',
    storageBucket: 'moviemio-app.firebasestorage.app',
    iosBundleId: 'com.example.moviemioApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLPfP5E_b6GxKFrg0zvF7K0tFZ91PzKb0',
    appId: '1:309940397515:web:aafbe8e7b532d59ab3c24e',
    messagingSenderId: '309940397515',
    projectId: 'moviemio-app',
    authDomain: 'moviemio-app.firebaseapp.com',
    storageBucket: 'moviemio-app.firebasestorage.app',
    measurementId: 'G-RETDNJ88ZF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAblwgjsyNWuDtm1GFRnO4OqsWqT_B3G8A',
    appId: '1:309940397515:ios:4730895756b32caab3c24e',
    messagingSenderId: '309940397515',
    projectId: 'moviemio-app',
    storageBucket: 'moviemio-app.firebasestorage.app',
    iosBundleId: 'com.example.moviemioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLPfP5E_b6GxKFrg0zvF7K0tFZ91PzKb0',
    appId: '1:309940397515:web:1a21439bf43278aab3c24e',
    messagingSenderId: '309940397515',
    projectId: 'moviemio-app',
    authDomain: 'moviemio-app.firebaseapp.com',
    storageBucket: 'moviemio-app.firebasestorage.app',
    measurementId: 'G-GEG1PY0MK5',
  );

}